backup rc

diff --git a/mine/rc_file/bashrc b/mine/rc_file/bashrc
--- a/mine/rc_file/bashrc
+++ b/mine/rc_file/bashrc
@@ -337,7 +337,6 @@ function 2ding
     fi
 }
 
-
 complete -c vcmd
 function vcmd
 {
@@ -348,61 +347,127 @@ function vcmd
         type $1
     fi
 }
+complete -F __rmake_cmd_HUB rmake
+function __rmake_cmd
+{
+    local cur="${COMP_WORDS[COMP_CWORD]}"
+    local REPO_ROOT_PATH=`repo info | grep "Mount path" | head -1 | grep -o '/.*/'`
+    local options="`cd $REPO_ROOT_PATH && make -pRrq : 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($1 !~ "^[#.]") {print $1}}' | egrep -v '^[^[:alnum:]]' | sort`"
+    COMPREPLY=( $(compgen -W "${options}" -- ${cur}) )
+}
+function __rmake_cmd_HUB
+{
+    repo info > /dev/null 2>&1
+    if [ $? != 0 ];then
+        echo "not in repo or sub folders"
+        return
+    fi
+    case $COMP_CWORD in
+    0)  ;;
+    1)  if [ ${COMP_WORDS[0]} == rmake ];then
+            eval __rmake_cmd
+        fi
+        ;;
+    esac
+}
+function rmake
+{
+	OPTIND=0
+    while getopts :h opt
+    do
+        case $opt in
+            h)  echo "Usage: rmake [-h] [REPO_MAKE_COMMAND]"
+                echo "       @REPO_MAKE_COMMAND: same as normal make command in repo"
+                echo "       @-h : show usage"
+				echo ""
+				echo "       You don't need to switch folder for compile now"
+				echo "       You can use this command in repo root folder or sub folders directly"
+				echo "       And rmake can auto completion"
+				return
+                ;;
+            ?)  echo "Invalid option, use -h to see usage"
+				return
+                ;;
+        esac
+    done
+    shift $((OPTIND - 1))
 
+    repo info > /dev/null 2>&1
+    if [ $? != 0 ];then
+        echo "not in repo or sub folders"
+        return
+    fi
+    export REPO_ROOT_PATH=`repo info | grep "Mount path" | head -1 | grep -o '/.*/'`
+    (cd $REPO_ROOT_PATH && eval make $*)
+}
 complete -c ccolor
 function ccolor
 {
-	local arr1=(warning YELLOW error RED failed RED fail RED note BLUE \
-				警告 YELLOW 错误 RED 附注 BLUE)
-	local RED="\033[0;31m"
-	local RED1="\033[1;031m"
-	local YELLOW="\033[0;33m"
-	local YELLOW1="\033[1;33m"
-	local BLUE="\033[0;34m"
-	local BLUE1="\033[1;34m"
-	local END="\033[0m"
-    
-	shopt -u expand_aliases
+    local arr1=(warning#YELLOW#error#RED#failed#RED#fail#RED#note#BLUE#\
+                警告#YELLOW#错误#RED#附注#BLUE#\
+				undefined reference#RED)
+    local except=("make setup" "")
+    local RED="\033[0;31m"
+    local RED1="\033[1;031m"
+    local YELLOW="\033[0;33m"
+    local YELLOW1="\033[1;33m"
+    local BLUE="\033[0;34m"
+    local BLUE1="\033[1;34m"
+    local END="\033[0m"
+
+    shopt -u expand_aliases
+
+	for ((i=0;i<${#except[@]};i++))
+    do
+        if [ z"${except[$i]}" == z"$*" ]
+        then
+            eval "$*"
+            shopt -s expand_aliases
+            return
+        fi
+    done
+
     eval "$*" 2>&1 | awk -v arr2="${arr1[*]}" '
-	BEGIN{n=split(arr2,arr3," ");normal_print=1}
-	{
+    BEGIN{n=split(arr2,arr3,"#");normal_print=1}
+    {
         IGNORECASE=1;
-		for(i=1;i<=n;i=i+2){
-       		 if((match($0,"[ \t:]+"arr3[i]"[s]*[ \t:]+"))||
-			    (match($0,"^"arr3[i]"[s]*[ \t:]+"))||
-				(match($0,"[ \t:]+"arr3[i]"[s]*$"))||
-				(match($0,"^"arr3[i]"[s]*$"))){
-       		     len_s=RLENGTH;
-				 pos=RSTART;
-       		     len=length($0);
-       		     pos1=pos+len_s;
-       		     b=substr($0, 1, pos-1);
-				 m=substr($0, pos, RLENGTH);
-       		     a=substr($0, pos1, len-pos1+1);
-       		     switch(arr3[i+1]){
-       		         case /YELLOW/:
-       		             print "'"$YELLOW"'"b"'"$YELLOW1"'"m"'"$YELLOW"'"a"'"$END"'";
-       		             break;
-       		         case /RED/:
-       		             print "'"$RED"'"b"'"$RED1"'"m"'"$RED"'"a"'"$END"'";
-       		             break;
-       		         case /BLUE/:
-       		             print "'"$BLUE"'"b"'"$BLUE1"'"m"'"$BLUE"'"a"'"$END"'";
-       		             break;
-       		         default:
-       		             print "Color setting wrong! Please check ~/.bashrc ccolor func"
-       		     }
-       		     normal_print=0;
-       		     break;
-       		 }
-    	}
-   		if(normal_print)
-        	print;
-    	else
-        	normal_print=1;
-	}'
+        for(i=1;i<=n;i=i+2){
+             if((match($0,"[ \t:]+"arr3[i]"[s]*[ \t:]+"))||
+                (match($0,"^"arr3[i]"[s]*[ \t:]+"))||
+                (match($0,"[ \t:]+"arr3[i]"[s]*$"))||
+                (match($0,"^"arr3[i]"[s]*$"))){
+                 len_s=RLENGTH;
+                 pos=RSTART;
+                 len=length($0);
+                 pos1=pos+len_s;
+                 b=substr($0, 1, pos-1);
+                 m=substr($0, pos, RLENGTH);
+                 a=substr($0, pos1, len-pos1+1);
+                 switch(arr3[i+1]){
+                     case /YELLOW/:
+                         print "'"$YELLOW"'"b"'"$YELLOW1"'"m"'"$YELLOW"'"a"'"$END"'";
+                         break;
+                     case /RED/:
+                         print "'"$RED"'"b"'"$RED1"'"m"'"$RED"'"a"'"$END"'";
+                         break;
+                     case /BLUE/:
+                         print "'"$BLUE"'"b"'"$BLUE1"'"m"'"$BLUE"'"a"'"$END"'";
+                         break;
+                     default:
+                         print "Color setting wrong! Please check ~/.bashrc ccolor func"
+                 }
+                 normal_print=0;
+                 break;
+             }
+        }
+        if(normal_print)
+            print;
+        else
+            normal_print=1;
+    }'
     shopt -s expand_aliases
 }
+
 alias gcc="ccolor gcc"
 alias g++="ccolor g++"
 alias make="ccolor make"
@@ -411,3 +476,71 @@ alias mmm="ccolor mmm"
 alias zhmakepkg="ccolor zhmakepkg"
 alias soter_make="ccolor soter_make"
 alias sboot_make="ccolor sboot_make"
+
+complete -F __goto_cmd_HUB goto
+function __goto_cmd
+{
+    local special_subfolders=("ree")
+    local regexp="find -maxdepth 1 -type d | sed '/^\.$\|^\.\/\.\.*/d' | sed 's/\.\///g'"
+
+    local cur="${COMP_WORDS[COMP_CWORD]}"
+    local REPO_ROOT_PATH=`repo info | grep "Mount path" | head -1 | grep -o '/.*/'`
+    local top_folders="`cd $REPO_ROOT_PATH && eval $regexp`"
+    local sub_folders=""
+    for sub_folder in ${special_subfolders[@]}
+    do
+		sub_folders="$sub_folders""`cd $REPO_ROOT_PATH/$sub_folder && eval "$regexp | sed 's/^/$sub_folder\//g'"`"
+    done
+    local options=$top_folders$sub_folders
+    COMPREPLY=( $(compgen -W "${options}" -- ${cur}) )
+}
+function __goto_cmd_HUB
+{
+    repo info > /dev/null 2>&1
+    if [ $? != 0 ];then
+        echo "not in repo or sub folders"
+        return
+    fi
+    case $COMP_CWORD in
+    0)  ;;
+    1)  if [ ${COMP_WORDS[0]} == goto ];then
+            eval __goto_cmd
+        fi
+        ;;
+    esac
+}
+function goto
+{
+    OPTIND=0
+    while getopts :h opt
+    do
+        case $opt in
+            h)  echo "Usage: goto [-h] [FOLDER_IN_REPO]"
+                echo "       @FOLDER_IN_REPO: top folders in repo root path or special sub folders"
+                echo "       @-h : show usage"
+                echo ""
+                echo "       You can jump to the fold interested by using goto"
+                echo "       You can use this command in repo root folder or sub folders directly"
+                echo "       And goto can auto completion"
+                return
+                ;;
+            ?)  echo "Invalid option, use -h to see usage"
+                return
+                ;;
+        esac
+    done
+    shift $((OPTIND - 1))
+
+    repo info > /dev/null 2>&1
+    if [ $? != 0 ];then
+        echo "not in repo or sub folders"
+        return
+    fi
+    local REPO_ROOT_PATH=`repo info | grep "Mount path" | head -1 | grep -o '/.*/'`
+
+    if [ $# -eq 0 ];then
+        cd $REPO_ROOT_PATH
+    else
+        cd $REPO_ROOT_PATH/$*
+    fi
+}
